=== roldanoteodavid/1dam/Markup languages/2ºEVALUACIÓN/XML/Assigment2_DavidRoldán/schema/ex4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" type="bookType" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="title" type="titleType" />
            <xs:element name="edition" type="editionType" minOccurs="0"/>
            <xs:element name="author" type="authorType" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="publishedDate" type="dateType" />
            <xs:element name="type" type="typeType" />
            <xs:element name="price" type="priceType" />
        </xs:sequence>
        <xs:attribute name="isbn" type="xs:string" use="required" />
    </xs:complexType>
    <xs:complexType name="titleType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="typeT" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="typeT">
        <xs:restriction base="xs:string">
            <xs:enumeration value="P" />
            <xs:enumeration value="H" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="editionType">
        <xs:restriction base="xs:byte" />
    </xs:simpleType>
    <xs:complexType name="authorType">
        <xs:sequence>
            <xs:element name="first" type="xs:string" />
            <xs:element name="middle" type="middleType" minOccurs="0" />
            <xs:element name="last" type="xs:string" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="middleType">
        <xs:restriction base="xs:string" >
            <xs:maxLength value="1" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="dateType">
        <xs:sequence>
            <xs:element name="month" type="monthType"/>
            <xs:element name="day" type="dayType" />
            <xs:element name="year" type="xs:gYear" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="monthType">
        <xs:restriction base="xs:unsignedByte">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="12" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dayType">
        <xs:restriction base="xs:unsignedByte">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="31" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="typeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="nonfiction" />
            <xs:enumeration value="fiction" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0.00" />
            <xs:pattern value="[0-9]{0,3}.[0-9]{2}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== roldanoteodavid/1dam/Markup languages/2ºEVALUACIÓN/XML/Assigment2_DavidRoldán/ex4.xml
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema/ex4.xsd">
    <book isbn="a1">
        <title type="P">Pepe pepe</title>
        <edition>12</edition>
        <author>
            <first>lqwj</first>
            <middle>r</middle>
            <last>sldfjsl</last>
        </author>
        <author>
            <first>lqwj</first>
            <middle>r</middle>
            <last>sldfjsl</last>
        </author>
        <publishedDate>
            <month>2</month>
            <day>1</day>
            <year>1999</year>
        </publishedDate>
        <type>nonfiction</type>
        <price>003.21</price>
    </book>
    <book isbn="b2">
        <title type="H">SKJFH</title>
        <edition>13</edition>
        <author>
            <first>lqwj</first>
            <middle>r</middle>
            <last>sldfjsl</last>
        </author>
        <publishedDate>
            <month>2</month>
            <day>1</day>
            <year>1979</year>
        </publishedDate>
        <type>fiction</type>
        <price>012.45</price>
    </book>
    <book isbn="c3">
        <title type="H">ALIJSCLK</title>
        <edition>14</edition>
        <author>
            <first>lqwj</first>
            <middle>r</middle>
            <last>sldfjsl</last>
        </author>
        <publishedDate>
            <month>5</month>
            <day>1</day>
            <year>1989</year>
        </publishedDate>
        <type>fiction</type>
        <price>031.45</price>
    </book>
</books>
