<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fruitstore [
 <!ELEMENT fruits (fruit+)>
 <!ELEMENT fruit (name,origins, price)>
 <!ELEMENT origins (origin+)>
 <!ELEMENT origin (#PCDATA)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT price (#PCDATA)>
 <!ELEMENT area (#PCDATA)>
 <!ELEMENT country (#PCDATA)>
 <!ATTLIST fruit code CDATA #REQUIRED>
 <!ATTLIST origin stock (yes|no) "no" #implied>
 ]>
<fruits>
    <fruit code="x-345" season="spring">
        <name>Strawberry</name>
        <origins>
            <origin stock="yes">
                <area>Madrid</area>
                <country>SP</country>
            </origin>
        </origins>
        <price>3.56</price>
    </fruit>
    <fruit code="e-12">
        <name>Banana</name>
        <origins>
            <origin>
                <area>Canarias</area>
                <country>SP</country>
            </origin>
        </origins>
        <price>3.56</price>
    </fruit>
    <fruit code="s-34">
        <name>Blueberry</name>
        <origins>
            <origin stock="no">
                <area>Chile</area>
                <country>Other</country>
            </origin>
            <origin>
                <area>South Africa</area>
                <country>Other</country>
            </origin>
        </origins>
        <price>3.56</price>
    </fruit>
</fruits>