=== roldanoteodavid/1dam/Markup languages/2ºEVALUACIÓN/XML/Examples/schema/Example6.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="shirt" type="ItemsType" minOccurs="0" />
                <xs:element name="hat" type="ItemsType" minOccurs="0" />
                <xs:element name="umbrella" type="ItemsType" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="ItemsType">
        <xs:sequence>
            <xs:element name="number" type="xs:string" />
            <xs:element name="name" type="xs:string" />
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="size" type="sizeType" />
                <xs:element name="color" type="colorType" />
                <xs:element name="description" type="xs:string" />
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="effDate" type="xs:date" default="1900-01-01" />
        <xs:anyAttribute namespace="##other" />
    </xs:complexType>
    <xs:complexType name="sizeType">
        <xs:simpleContent>
            <xs:extension base="xs:integer">
                <xs:attribute name="system" type="xs:token" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="colorType">
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>
</xs:schema>

=== roldanoteodavid/1dam/Markup languages/2ºEVALUACIÓN/XML/Examples/Example6.3.xml
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema/Example6.3.xsd">
    <shirt effDate="2002-04-02">
        <number>557</number>
        <name>Short-Sleeved Linen Blouse</name>
        <size system="US-DRESS">10</size>
        <color value="blue" />
        <description>
            This shirt is the best-selling shirt in
            our catalog
        </description>
    </shirt>
    <hat>
        <number>557</number>
        <name>Ten-Gallon Hat</name>
        <color value="red" />
    </hat>
</items>
