=== roldanoteodavid/1dam/Markup languages/2ºEVALUACIÓN/XML/Examples/schema/note.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="note">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="to" type="xs:string" />
        <xs:element name="from" type="xs:string" />
        <xs:element name="heading" type="xs:string" />
        <xs:element name="body" type="xs:string" />
        <xs:element name="job" type="xs:string" default="unemployed" />
        <xs:element name="language" type="xs:string" fixed="Spanish" />

        <xs:element name="brothers">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:minInclusive value="0" />
              <xs:maxInclusive value="10" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="mobile">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Huawey" />
              <xs:enumeration value="Samsung" />
              <xs:enumeration value="Xiaomi" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== roldanoteodavid/1dam/Markup languages/2ºEVALUACIÓN/XML/Examples/note.xml
<?xml version="1.0" encoding="UTF-8"?>
<note xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema/note.xsd">
    <to>Tove</to>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend</body>
    <job>Teacher</job>
    <language>Spanish</language>
    <brothers>5</brothers>
    <mobile>Xiaomi</mobile>
</note>
